
    <section class="topnav">

        <table>
            <tr>
                <td id="special_td"><img src="images/logo.png" alt="logo" height="70" width="250"/></td>
                <td>
                    <a href="index.php">Main</a>
                </td>

                <td>
                    <a href="enquire.php">Enquire</a>
                </td>

                <td >
                    <a href="product.php">Product</a>
                </td>

                <td>
                    <a href="about.php">About</a>
                </td>

                <td id="current">
                    <a href="enhancements.php">Enhancements</a>
                </td>
            </tr>
        </table>
    </section>
